#!/bin/bash

dockerUID=$(id -u)
dockerGID=$(id -g)

mkdir dbdata

echo "Container build in progress.."
composer_docker_hash=$(docker build -q .)
docker run --user $dockerUID:$dockerGID --rm -v ./laravel:/var/www/html -it $composer_docker_hash composer install
cp env_docker laravel/.env
cp env_docker .env
echo "dockerUID=$dockerUID" >> .env
echo "dockerGID=$dockerGID" >> .env
docker compose up -d
sleep 5
docker compose exec app php artisan key:generate
docker compose exec app php artisan config:cache
while true; do sleep 3s && docker compose exec app php artisan migrate:fresh && break; done
docker compose exec app php artisan db:seed
docker compose exec app php artisan test
docker compose down
